### ISSUE TITLE
Starters.md nuxt js link

### ISSUE THREAD

**Issue by porkus1990** [Contentrain/contentrain-docs#1]
### What's wrong?

in starters.md, the link to Nuxtjs is wrong.
https://nextjs.org/ should be https://nuxtjs.org/

### How to fix?
change `[Nuxtjs](https://nextjs.org/)` to `[Nuxtjs](https://nuxtjs.org/)`

**Comment by ABB65** [comment]
Hi, We manage our docs using Contentrain :). Thank you for your feedback I have just fixed it.
